PRAGMA foreign_keys=ON;

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  first_name TEXT,
  last_name TEXT,
  username TEXT UNIQUE,
  gender TEXT CHECK(gender IN ('male','female','other')),
  seeking TEXT CHECK(seeking IN ('male','female','both')) DEFAULT 'both',
  bio TEXT CHECK(length(bio) <= 5000) DEFAULT '',
  avatar_path TEXT,
  lat REAL,
  lng REAL,
  radius_km INTEGER DEFAULT 50,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS photos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  path TEXT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- 40 Likert answers per user (1..5). We'll store as q1..q40.
CREATE TABLE IF NOT EXISTS answers (
  user_id INTEGER PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
  q1 INTEGER,  q2 INTEGER,  q3 INTEGER,  q4 INTEGER,  q5 INTEGER,
  q6 INTEGER,  q7 INTEGER,  q8 INTEGER,  q9 INTEGER,  q10 INTEGER,
  q11 INTEGER, q12 INTEGER, q13 INTEGER, q14 INTEGER, q15 INTEGER,
  q16 INTEGER, q17 INTEGER, q18 INTEGER, q19 INTEGER, q20 INTEGER,
  q21 INTEGER, q22 INTEGER, q23 INTEGER, q24 INTEGER, q25 INTEGER,
  q26 INTEGER, q27 INTEGER, q28 INTEGER, q29 INTEGER, q30 INTEGER,
  q31 INTEGER, q32 INTEGER, q33 INTEGER, q34 INTEGER, q35 INTEGER,
  q36 INTEGER, q37 INTEGER, q38 INTEGER, q39 INTEGER, q40 INTEGER
);
